version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}